From 217c717d0fe3c0c4801725ac43da5564382e13a4 Mon Sep 17 00:00:00 2001
From: Zen <z@pyl.onl>
Date: Mon, 17 Feb 2025 17:09:03 -0600
Subject: [PATCH 58/58] reattempt livecd mounts on failure

Signed-off-by: Zen <z@pyl.onl>
---
 src/ugrd/fs/livecd.py | 11 ++++++++---
 1 file changed, 8 insertions(+), 3 deletions(-)

diff --git a/src/ugrd/fs/livecd.py b/src/ugrd/fs/livecd.py
index 5ba3bf5..4dd97e5 100644
--- a/src/ugrd/fs/livecd.py
+++ b/src/ugrd/fs/livecd.py
@@ -1,5 +1,5 @@
 __author__ = "desultory"
-__version__ = "0.6.0"
+__version__ = "0.7.0"
 
 from zenlib.util import contains
 
@@ -13,13 +13,18 @@ def mount_livecd(self) -> str:
     Because this mount is made manulally, no mount entry/validation/unmounting is done
     All mount handling happens strictly at runtime
     """
-    return """
+    return f"""
     livecd_label="$(readvar livecd_label)"
     if [ -z "$livecd_label" ]; then
         rd_fail "livecd_label must be set to the label of the livecd storage root."
     fi
     einfo "Mounting livecd with label: $livecd_label"
-    mount LABEL="$livecd_label" /run/livecd || rd_fail "Failed to mount livecd with label: $livecd_label"
+    while ! mount LABEL="$livecd_label" /run/livecd 2>/dev/null; do
+        eerror "Failed to mount livecd with label: $livecd_label"
+        if prompt_user "Press enter to break, waiting: {self["mount_timeout"]}s" {self["mount_timeout"]}; then
+            rd_fail "Failed to mount livecd with label: $livecd_label"
+        fi
+    done
     """
 
 
-- 
2.48.1

